name: Test Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build site
      run: npm run build
    
    - name: Test all links
      run: npm run test:links
    
    - name: Upload link test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: broken-links-report
        path: |
          dist/
          !dist/node_modules/